// extensions/interfaces/product-generator/src/components/ProductList.vue
<script setup lang="ts">
import { ref, onMounted, watch } from 'vue';
import type { Product } from '../types';
import ProductDetail from './ProductDetail.vue';

const props = defineProps<{
  farmId: string
}>();

const products = ref<Product[]>([]);
const loading = ref(false);
const error = ref<string | null>(null);
const selectedProduct = ref<Product | null>(null);
const generatingProduct = ref<string | null>(null);

const fetchProducts = async () => {
  try {
    loading.value = true;
    const response = await fetch(`/api/ext/product-generator/farms/${props.farmId}/products`);
    
    if (!response.ok) {
      throw new Error('Nepodařilo se načíst produkty');
    }
    
    products.value = await response.json();
    error.value = null;
  } catch (err) {
    error.value = err instanceof Error ? err.message : 'Nastala neočekávaná chyba';
  } finally {
    loading.value = false;
  }
};

const generateDescriptions = async (productId: string) => {
  try {
    generatingProduct.value = productId;
    const response = await fetch(`/api/ext/product-generator/products/${productId}/generate-descriptions`, {
      method: 'POST'
    });
    
    if (!response.ok) {
      throw new Error('Nepodařilo se vygenerovat popisky');
    }
    
    await fetchProducts();
  } catch (err) {
    error.value = err instanceof Error ? err.message : 'Nastala chyba při generování popisků';
  } finally {
    generatingProduct.value = null;
  }
};

const generateImages = async (productId: string) => {
  try {
    generatingProduct.value = productId;
    const response = await fetch(`/api/ext/product-generator/products/${productId}/generate-images`, {
      method: 'POST'
    });
    
    if (!response.ok) {
      throw new Error('Nepodařilo se vygenerovat obrázky');
    }
    
    await fetchProducts();
  } catch (err) {
    error.value = err instanceof Error ? err.message : 'Nastala chyba při generování obrázků';
  } finally {
    generatingProduct.value = null;
  }
};

watch(() => props.farmId, fetchProducts, { immediate: true });

const getStatusIcon = (status: Product['status']) => {
  switch (status) {
    case 'completed': return '✅';
    case 'in_progress': return '🔄';
    default: return '⏳';
  }
};
</script>

<template>
  <div class="product-list">
    <div v-if="loading" class="loading">Načítání produktů...</div>
    
    <div v-else-if="error" class="error">{{ error }}</div>
    
    <div v-else-if="products.length === 0" class="no-products">
      Pro tuto farmu zatím nebyly importovány žádné produkty
    </div>
    
    <div v-else class="products-grid">
      <div 
        v-for="product in products" 
        :key="product.id" 
        class="product-card"
        @click="selectedProduct = product"
      >
        <div class="product-header">
          <h3>{{ product.name }}</h3>
          <span class="status-icon">
            {{ getStatusIcon(product.status) }}
          </span>
        </div>
        
        <div class="product-sku">SKU: {{ product.shop_sku }}</div>
        
        <div class="product-actions">
          <button 
            @click.stop="generateDescriptions(product.id)"
            :disabled="product.status === 'completed' || generatingProduct === product.id"
          >
            Generovat popis
          </button>
          <button 
            @click.stop="generateImages(product.id)"
            :disabled="product.status === 'completed' || generatingProduct === product.id"
          >
            Generovat obrázky
          </button>
        </div>
      </div>
    </div>

    <ProductDetail 
      v-if="selectedProduct"
      :product="selectedProduct"
      @close="selectedProduct = null"
      @update="fetchProducts"
    />
  </div>
</template>

<style scoped>
.product-list {
  width: 100%;
}

.products-grid {
  display: grid;
  grid-template-columns: repeat(auto-fill, minmax(200px, 1fr));
  gap: 1rem;
}

.product-card {
  border: 1px solid #e0e0e0;
  border-radius: 8px;
  padding: 1rem;
  cursor: pointer;
  transition: box-shadow 0.3s;
}

.product-card:hover {
  box-shadow: 0 4px 6px rgba(0, 0, 0, 0.1);
}

.product-header {
  display: flex;
  justify-content: space-between;
  align-items: center;
  margin-bottom: 0.5rem;
}

.product-header h3 {
  margin: 0;
}

.status-icon {
  font-size: 1rem;
}

.product-sku {
  color: #666;
  margin-bottom: 0.5rem;
}

.product-actions {
  display: flex;
  gap: 0.5rem;
}

.product-actions button {
  flex: 1;
  padding: 0.5rem;
  border: none;
  border-radius: 4px;
  background-color: #2196f3;
  color: white;
  cursor: pointer;
}

.product-actions button:disabled {
  background-color: #ccc;
  cursor: not-allowed;
}

.loading, .error, .no-products {
  text-align: center;
  padding: 2rem;
  color: #666;
}

.error {
  color: #f44336;
}
</style>

// extensions/interfaces/product-generator/src/components/ProductList.tsx
import React, { useState, useEffect } from 'react';
import { RefreshCw, FileText, Image, Check, AlertTriangle } from 'lucide-react';
import { Alert, AlertDescription } from '../components/ui/alert';
import ProductDetail from './ProductDetail';

type Product = {
  id: string;
  name: string;
  shop_sku: string;
  generated_short_description: string;
  generated_long_description: string;
  ingredients: string;
  selected_image_url: string;
  status: 'draft' | 'in_progress' | 'completed';
};

interface ProductListProps {
  farmId: string;
}

const ProductList = ({ farmId }: ProductListProps) => {
  const [products, setProducts] = useState<Product[]>([]);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [generatingProduct, setGeneratingProduct] = useState<string | null>(null);
  const [selectedProductId, setSelectedProductId] = useState<string | null>(null);

  useEffect(() => {
    if (farmId) {
      fetchProducts();
    }
  }, [farmId]);

  const fetchProducts = async () => {
    try {
      setLoading(true);
      const response = await fetch(`/api/ext/product-generator/farms/${farmId}/products`);
      if (!response.ok) throw new Error('Nepodařilo se načíst produkty');
      const data = await response.json();
      setProducts(data);
    } catch (err) {
      setError('Nepodařilo se načíst produkty');
    } finally {
      setLoading(false);
    }
  };

  const generateDescriptions = async (productId: string) => {
    try {
      setGeneratingProduct(productId);
      const response = await fetch(`/api/ext/product-generator/products/${productId}/generate-descriptions`, {
        method: 'POST'
      });
      if (!response.ok) throw new Error('Nepodařilo se vygenerovat popisky');
      
      await fetchProducts();
    } catch (err) {
      setError('Nepodařilo se vygenerovat popisky');
    } finally {
      setGeneratingProduct(null);
    }
  };

  const generateImages = async (productId: string) => {
    try {
      setGeneratingProduct(productId);
      const response = await fetch(`/api/ext/product-generator/products/${productId}/generate-images`, {
        method: 'POST'
      });
      if (!response.ok) throw new Error('Nepodařilo se vygenerovat obrázky');
      
      await fetchProducts();
    } catch (err) {
      setError('Nepodařilo se vygenerovat obrázky');
    } finally {
      setGeneratingProduct(null);
    }
  };

  const getStatusIcon = (status: Product['status']) => {
    switch (status) {
      case 'completed':
        return <Check className="w-5 h-5 text-green-500" />;
      case 'in_progress':
        return <RefreshCw className="w-5 h-5 text-blue-500" />;
      default:
        return <AlertTriangle className="w-5 h-5 text-yellow-500" />;
    }
  };

  if (loading) {
    return (
      <div className="flex justify-center items-center h-64">
        <RefreshCw className="w-8 h-8 animate-spin text-blue-600" />
      </div>
    );
  }

  return (
    <div className="space-y-4">
      {error && (
        <Alert variant="destructive">
          <AlertDescription>{error}</AlertDescription>
        </Alert>
      )}

      <div className="overflow-x-auto rounded-lg border border-gray-200">
        <table className="min-w-full divide-y divide-gray-200">
          <thead className="bg-gray-50">
            <tr>
              <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                Produkt
              </th>
              <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                SKU
              </th>
              <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                Status
              </th>
              <th className="px-6 py-3 text-right text-xs font-medium text-gray-500 uppercase tracking-wider">
                Akce
              </th>
            </tr>
          </thead>
          <tbody className="bg-white divide-y divide-gray-200">
            {products.map((product) => (
              <tr 
                key={product.id}
                onClick={() => setSelectedProductId(product.id)}
                className="cursor-pointer hover:bg-gray-50"
              >
                <td className="px-6 py-4 whitespace-nowrap">
                  <div className="font-medium text-gray-900">{product.name}</div>
                </td>
                <td className="px-6 py-4 whitespace-nowrap">
                  <div className="text-sm text-gray-500">{product.shop_sku}</div>
                </td>
                <td className="px-6 py-4 whitespace-nowrap">
                  <div className="flex items-center">
                    {getStatusIcon(product.status)}
                    <span className="ml-2 text-sm text-gray-500">
                      {product.status === 'completed' ? 'Dokončeno' : 
                       product.status === 'in_progress' ? 'Zpracovává se' : 'Čeká na zpracování'}
                    </span>
                  </div>
                </td>
                <td className="px-6 py-4 whitespace-nowrap text-right">
                  <button
                    onClick={(e) => {
                      e.stopPropagation();
                      generateDescriptions(product.id);
                    }}
                    disabled={generatingProduct === product.id}
                    className="inline-flex items-center px-3 py-1 border border-transparent text-sm font-medium rounded-md text-blue-700 bg-blue-100 hover:bg-blue-200 mr-2 disabled:opacity-50"
                  >
                    <FileText className="w-4 h-4 mr-1" />
                    Popisky
                  </button>
                  <button
                    onClick={(e) => {
                      e.stopPropagation();
                      generateImages(product.id);
                    }}
                    disabled={generatingProduct === product.id}
                    className="inline-flex items-center px-3 py-1 border border-transparent text-sm font-medium rounded-md text-purple-700 bg-purple-100 hover:bg-purple-200 disabled:opacity-50"
                  >
                    <Image className="w-4 h-4 mr-1" />
                    Obrázky
                  </button>
                </td>
              </tr>
            ))}
          </tbody>
        </table>
      </div>

      {selectedProductId && (
        <ProductDetail
          productId={selectedProductId}
          onClose={() => setSelectedProductId(null)}
        />
      )}
    </div>
  );
};

export default ProductList;
