// extensions/interfaces/product-generator/src/components/ProductGenerator.tsx
import React, { useState, useEffect } from 'react';
import { Plus, Upload, RefreshCw } from 'lucide-react';
import { Alert, AlertDescription } from '../components/ui/alert';
import AddFarmModal from './AddFarmModal';
import ProductList from './ProductList';

// Definice typů pro TypeScript
type Farm = {
  id: string;
  name: string;
  farm_id: string;
  import_file?: string;
  created_at: Date;
  updated_at: Date;
};

interface ProductGeneratorProps {
  // Directus specific props
  value?: string;
  onChange?: (value: string) => void;
  width: string;
  height: string;
}

const ProductGenerator: React.FC<ProductGeneratorProps> = ({ value, onChange, width, height }) => {
  // Stavové proměnné
  const [farms, setFarms] = useState<Farm[]>([]);
  const [selectedFarm, setSelectedFarm] = useState<Farm | null>(null);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [showAddFarmModal, setShowAddFarmModal] = useState(false);

  // Načtení farem při prvním renderu
  useEffect(() => {
    fetchFarms();
  }, []);

  // Načtení seznamu farem
  const fetchFarms = async () => {
    try {
      setLoading(true);
      const response = await fetch('/api/ext/product-generator/farms');
      
      if (!response.ok) {
        throw new Error('Nepodařilo se načíst farmy');
      }
      
      const data = await response.json();
      setFarms(data);
      setError(null);
    } catch (err) {
      setError(err instanceof Error ? err.message : 'Nastala neočekávaná chyba');
    } finally {
      setLoading(false);
    }
  };

  // Handler pro přidání nové farmy
  const handleAddFarm = async (formData: FormData) => {
    try {
      setLoading(true);
      const response = await fetch('/api/ext/product-generator/farms', {
        method: 'POST',
        body: formData
      });
      
      if (!response.ok) {
        throw new Error('Nepodařilo se vytvořit farmu');
      }
      
      await fetchFarms();
      setShowAddFarmModal(false);
    } catch (err) {
      setError(err instanceof Error ? err.message : 'Nastala neočekávaná chyba');
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="flex h-screen bg-white">
      {/* Sidebar */}
      <div className="w-64 border-r border-gray-200 p-4">
        <div className="flex items-center justify-between mb-6">
          <h2 className="text-xl font-semibold text-gray-800">Farmy</h2>
          <button
            onClick={() => setShowAddFarmModal(true)}
            className="p-2 text-blue-600 hover:text-blue-800"
            title="Přidat farmu"
          >
            <Plus size={20} />
          </button>
        </div>

        {/* Seznam farem */}
        {loading ? (
          <div className="flex items-center justify-center py-4">
            <RefreshCw className="animate-spin text-blue-600" />
          </div>
        ) : (
          <div className="space-y-2">
            {farms.map((farm) => (
              <div
                key={farm.id}
                onClick={() => setSelectedFarm(farm)}
                className={`p-3 rounded-lg cursor-pointer transition-colors ${
                  selectedFarm?.id === farm.id
                    ? 'bg-blue-100 text-blue-800'
                    : 'hover:bg-gray-100'
                }`}
              >
                <div className="font-medium">{farm.name}</div>
                <div className="text-sm text-gray-500">ID: {farm.farm_id}</div>
              </div>
            ))}
          </div>
        )}

        {error && (
          <Alert className="mt-4" variant="destructive">
            <AlertDescription>{error}</AlertDescription>
          </Alert>
        )}
      </div>

      {/* Hlavní obsah */}
      <div className="flex-1 p-6">
        {selectedFarm ? (
          <div>
            <h1 className="text-2xl font-bold text-gray-900 mb-6">
              {selectedFarm.name}
            </h1>
            <ProductList farmId={selectedFarm.id} />
          </div>
        ) : (
          <div className="flex flex-col items-center justify-center h-full text-gray-500">
            <Upload size={48} className="mb-4" />
            <p>Vyberte farmu ze seznamu nebo vytvořte novou</p>
          </div>
        )}
      </div>

      {/* Modální okno pro přidání farmy */}
      <AddFarmModal 
        isOpen={showAddFarmModal}
        onClose={() => setShowAddFarmModal(false)}
        onSubmit={handleAddFarm}
      />
    </div>
  );
};

export default ProductGenerator;

// extensions/interfaces/product-generator/src/components/ProductGenerator.vue
<script setup lang="ts">
import { ref, onMounted } from 'vue';
import type { Farm, Product } from '../types';
import ProductList from './ProductList.vue';
import AddFarmModal from './AddFarmModal.vue';

const farms = ref<Farm[]>([]);
const selectedFarm = ref<Farm | null>(null);
const loading = ref(false);
const error = ref<string | null>(null);
const showAddFarmModal = ref(false);

const fetchFarms = async () => {
  try {
    loading.value = true;
    const response = await fetch('/api/ext/product-generator/farms');
    
    if (!response.ok) {
      throw new Error('Nepodařilo se načíst farmy');
    }
    
    farms.value = await response.json();
    error.value = null;
  } catch (err) {
    error.value = err instanceof Error ? err.message : 'Nastala neočekávaná chyba';
  } finally {
    loading.value = false;
  }
};

const handleAddFarm = async (farmData: FormData) => {
  try {
    loading.value = true;
    const response = await fetch('/api/ext/product-generator/farms', {
      method: 'POST',
      body: farmData
    });
    
    if (!response.ok) {
      throw new Error('Nepodařilo se vytvořit farmu');
    }
    
    await fetchFarms();
    showAddFarmModal.value = false;
  } catch (err) {
    error.value = err instanceof Error ? err.message : 'Nastala neočekávaná chyba';
  } finally {
    loading.value = false;
  }
};

onMounted(fetchFarms);
</script>

<template>
  <div class="product-generator">
    <div v-if="loading" class="loading">Načítání...</div>
    
    <div v-else-if="error" class="error">{{ error }}</div>
    
    <div v-else class="content">
      <div class="sidebar">
        <div class="sidebar-header">
          <h2>Farmy</h2>
          <button 
            @click="showAddFarmModal = true" 
            class="add-farm-btn"
          >
            Přidat farmu
          </button>
        </div>
        
        <div class="farm-list">
          <div 
            v-for="farm in farms" 
            :key="farm.id"
            :class="['farm-item', { active: selectedFarm?.id === farm.id }]"
            @click="selectedFarm = farm"
          >
            <div class="farm-name">{{ farm.name }}</div>
            <div class="farm-id">ID: {{ farm.farm_id }}</div>
          </div>
        </div>
      </div>
      
      <div class="main-content">
        <template v-if="selectedFarm">
          <h2>{{ selectedFarm.name }}</h2>
          <ProductList :farm-id="selectedFarm.id" />
        </template>
        <div v-else class="no-selection">
          Vyberte farmu ze seznamu
        </div>
      </div>
    </div>
    
    <AddFarmModal 
      v-if="showAddFarmModal"
      @close="showAddFarmModal = false"
      @submit="handleAddFarm"
    />
  </div>
</template>

<style scoped>
.product-generator {
  display: flex;
  height: 100%;
  background: white;
}

.sidebar {
  width: 250px;
  border-right: 1px solid #e0e0e0;
  padding: 1rem;
}

.sidebar-header {
  display: flex;
  justify-content: space-between;
  align-items: center;
  margin-bottom: 1rem;
}

.add-farm-btn {
  width: 100%;
  padding: 0.5rem;
  margin-bottom: 1rem;
  background: #2196f3;
  color: white;
  border: none;
  border-radius: 4px;
  cursor: pointer;
}

.add-farm-btn:hover {
  background: #1976d2;
}

.farm-list {
  display: flex;
  flex-direction: column;
}

.farm-item {
  padding: 0.5rem;
  cursor: pointer;
  border-radius: 4px;
}

.farm-item:hover {
  background: #f5f5f5;
}

.farm-item.active {
  background: #e0e0e0;
}

.farm-item .farm-name {
  font-weight: bold;
}

.farm-item .farm-id {
  font-size: 0.8rem;
  color: #666;
}

.main-content {
  flex: 1;
  padding: 1rem;
}

.loading, .error, .no-selection {
  padding: 2rem;
  text-align: center;
  color: #666;
}

.error {
  color: #f44336;
}
</style>
